/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DomainRegistryV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "changeDomainHolderReward"
      | "changeRegistrationPrice"
      | "domainHolderReward"
      | "findDomainHolderBy"
      | "getDomainRewardBalance"
      | "getTotalRewardBalance"
      | "initialize"
      | "isDomainRegistered"
      | "owner"
      | "registerDomain"
      | "registrationPrice"
      | "renounceOwnership"
      | "transferOwnership"
      | "withdraw"
      | "withdrawRewardFor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DomainRegistered"
      | "Initialized"
      | "OwnershipTransferred"
      | "RewardApplied"
      | "RewardWithdrawed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "changeDomainHolderReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeRegistrationPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "domainHolderReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "findDomainHolderBy",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainRewardBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRewardBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isDomainRegistered",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDomain",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registrationPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawRewardFor",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeDomainHolderReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeRegistrationPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainHolderReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findDomainHolderBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainRewardBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRewardBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDomainRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRewardFor",
    data: BytesLike
  ): Result;
}

export namespace DomainRegisteredEvent {
  export type InputTuple = [
    indexedName: string,
    indexedDomainHolder: AddressLike,
    name: string,
    domainHolder: AddressLike,
    createdDate: BigNumberish
  ];
  export type OutputTuple = [
    indexedName: string,
    indexedDomainHolder: string,
    name: string,
    domainHolder: string,
    createdDate: bigint
  ];
  export interface OutputObject {
    indexedName: string;
    indexedDomainHolder: string;
    name: string;
    domainHolder: string;
    createdDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardAppliedEvent {
  export type InputTuple = [
    indexedDomainName: string,
    indexedDomainHolder: AddressLike,
    domainName: string,
    domainHolder: AddressLike,
    rewardValue: BigNumberish,
    rewardBalance: BigNumberish
  ];
  export type OutputTuple = [
    indexedDomainName: string,
    indexedDomainHolder: string,
    domainName: string,
    domainHolder: string,
    rewardValue: bigint,
    rewardBalance: bigint
  ];
  export interface OutputObject {
    indexedDomainName: string;
    indexedDomainHolder: string;
    domainName: string;
    domainHolder: string;
    rewardValue: bigint;
    rewardBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardWithdrawedEvent {
  export type InputTuple = [
    indexedDomainName: string,
    indexedDomainHolder: AddressLike,
    domainName: string,
    domainHolder: AddressLike,
    withdrawValue: BigNumberish
  ];
  export type OutputTuple = [
    indexedDomainName: string,
    indexedDomainHolder: string,
    domainName: string,
    domainHolder: string,
    withdrawValue: bigint
  ];
  export interface OutputObject {
    indexedDomainName: string;
    indexedDomainHolder: string;
    domainName: string;
    domainHolder: string;
    withdrawValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DomainRegistryV2 extends BaseContract {
  connect(runner?: ContractRunner | null): DomainRegistryV2;
  waitForDeployment(): Promise<this>;

  interface: DomainRegistryV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeDomainHolderReward: TypedContractMethod<
    [toValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeRegistrationPrice: TypedContractMethod<
    [toValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  domainHolderReward: TypedContractMethod<[], [bigint], "view">;

  findDomainHolderBy: TypedContractMethod<
    [domainName: string],
    [string],
    "view"
  >;

  getDomainRewardBalance: TypedContractMethod<
    [domainName: string],
    [bigint],
    "view"
  >;

  getTotalRewardBalance: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [owner_: AddressLike, registrationPrice_: BigNumberish],
    [void],
    "nonpayable"
  >;

  isDomainRegistered: TypedContractMethod<
    [domainName: string],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerDomain: TypedContractMethod<[domainName: string], [void], "payable">;

  registrationPrice: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  withdrawRewardFor: TypedContractMethod<
    [domainName: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeDomainHolderReward"
  ): TypedContractMethod<[toValue: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeRegistrationPrice"
  ): TypedContractMethod<[toValue: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "domainHolderReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "findDomainHolderBy"
  ): TypedContractMethod<[domainName: string], [string], "view">;
  getFunction(
    nameOrSignature: "getDomainRewardBalance"
  ): TypedContractMethod<[domainName: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalRewardBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [owner_: AddressLike, registrationPrice_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDomainRegistered"
  ): TypedContractMethod<[domainName: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDomain"
  ): TypedContractMethod<[domainName: string], [void], "payable">;
  getFunction(
    nameOrSignature: "registrationPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRewardFor"
  ): TypedContractMethod<[domainName: string], [void], "nonpayable">;

  getEvent(
    key: "DomainRegistered"
  ): TypedContractEvent<
    DomainRegisteredEvent.InputTuple,
    DomainRegisteredEvent.OutputTuple,
    DomainRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardApplied"
  ): TypedContractEvent<
    RewardAppliedEvent.InputTuple,
    RewardAppliedEvent.OutputTuple,
    RewardAppliedEvent.OutputObject
  >;
  getEvent(
    key: "RewardWithdrawed"
  ): TypedContractEvent<
    RewardWithdrawedEvent.InputTuple,
    RewardWithdrawedEvent.OutputTuple,
    RewardWithdrawedEvent.OutputObject
  >;

  filters: {
    "DomainRegistered(string,address,string,address,uint256)": TypedContractEvent<
      DomainRegisteredEvent.InputTuple,
      DomainRegisteredEvent.OutputTuple,
      DomainRegisteredEvent.OutputObject
    >;
    DomainRegistered: TypedContractEvent<
      DomainRegisteredEvent.InputTuple,
      DomainRegisteredEvent.OutputTuple,
      DomainRegisteredEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardApplied(string,address,string,address,uint256,uint256)": TypedContractEvent<
      RewardAppliedEvent.InputTuple,
      RewardAppliedEvent.OutputTuple,
      RewardAppliedEvent.OutputObject
    >;
    RewardApplied: TypedContractEvent<
      RewardAppliedEvent.InputTuple,
      RewardAppliedEvent.OutputTuple,
      RewardAppliedEvent.OutputObject
    >;

    "RewardWithdrawed(string,address,string,address,uint256)": TypedContractEvent<
      RewardWithdrawedEvent.InputTuple,
      RewardWithdrawedEvent.OutputTuple,
      RewardWithdrawedEvent.OutputObject
    >;
    RewardWithdrawed: TypedContractEvent<
      RewardWithdrawedEvent.InputTuple,
      RewardWithdrawedEvent.OutputTuple,
      RewardWithdrawedEvent.OutputObject
    >;
  };
}
