/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DomainRegistry } from "./DomainRegistry";
export type { DomainRegistryV2 } from "./DomainRegistryV2";
