/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DomainRegistry__factory } from "./DomainRegistry__factory";
export { DomainRegistryV2__factory } from "./DomainRegistryV2__factory";
